Adding support for singularity containers
ML4GW/pyomicron pull request #1
Opened 2022-12-21 20:54 UTC by alecgunny

2022-12-27 15:16 UTC, EthanMarx requested changes
Looks great. One minor typeo fix and should be good. 

I am new to apptainer so want to clarify the picture here: 

We will be launching the pyomicron process inside the `/ml4gw/bbhnet` `apptainer` image. This will create and submit a condor dag which contains omicron jobs that run inside this image, and point to the omicron executable we have installed inside the image.

Is this setup compatible with using the LDG condor scheduler/ accessing all the LDG nodes?

2022-12-27 15:16 UTC, EthanMarx commented on omicron/cli/process.py
> +            singularity_image=args.singulatiy_image, **condorcmds)
Small typeo here: `singulatiy_image` --> `singularity_image`

2022-12-27 23:06 UTC, alecgunny commented on omicron/cli/process.py
> +            singularity_image=args.singulatiy_image, **condorcmds)
good catch

2022-12-27 23:08 UTC, alecgunny commented
Yeah that's exactly it. As far as I understand, it should be so long as you bind the `/etc/condor` directory into the container used to launch the jobs so that it has access to the appropriate condor configs, e.g.
```console
apptainer exec --bind /etc/condor:/etc/condor /cvmfs/singularity.opensciencegrid.org/ml4gw/bbhnet:main ...
```

2022-12-28 15:09 UTC, EthanMarx approved these changes

2022-12-28 15:10 UTC, EthanMarx approved these changes

2022-12-28 15:11 UTC, EthanMarx commented
Think I need write access for my review to count

2022-12-28 20:12 UTC, merged